=== Vedanshi15/Ticket-System/xml/user.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="userid" type="xs:positiveInteger"/>
              <xs:element name="username" type="xs:string"/>
              <xs:element name="password" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="usertype" type="types"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="types">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Admin"/>
      <xs:enumeration value="Client"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Vedanshi15/Ticket-System/xml/user.xml
<?xml version="1.0" encoding="utf-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
  <user>
    <userid>101</userid>
    <username>Vedanshi</username>
    <password>16ae16405d732e01616e6f5460dfeddc</password>
    <email>vedu2673@outlook.com</email>
    <usertype>Client</usertype>
  </user>
  <user>
    <userid>102</userid>
    <username>Zoya</username>
    <password>4bcc32e608d0a8e2d5c555f1d894ec51</password>
    <email>Zoyapatel23@yahoo.com</email>
    <usertype>Admin</usertype>
  </user>
  <user>
    <userid>103</userid>
    <username>Zeel</username>
    <password>1e21e6830003fcb8d9621df8223f4155</password>
    <email>zeel01@outlook.com</email>
    <usertype>Client</usertype>
  </user>
  <user>
    <userid>104</userid>
    <username>Keya</username>
    <password>c61f143c37f7c9b1b17e66ca15f00417</password>
    <email>Keya3748@gmail.com</email>
    <usertype>Client</usertype>
  </user>
</users>
